#!/bin/bash
while getopts :
if [-z "$POWER" ] || [ -z "$DIVIDE" ]; then echo "Erreur : POWER ou DIVIDE n'est pas defini." >&2
					    exit 1
fi

if ["$DIVIDE" -eq 0 ]; then
    echo "Erreur : division par zero." >&2
    exit 1
fi

result=$((POWER / DIVIDE))

echo "$result"
